name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
      - name: Debug Secrets
        run: echo "VERCEL_TOKEN is set"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: success()  # Ensures it only runs if the previous job succeeded
    steps:
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Deploy job is running"
          npx vercel deploy --prod --token $VERCEL_TOKEN --confirm
